version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 10s
      retries: 5

  backend:
    build: ./backend
    container_name: springboot-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: react-app
    depends_on:
      - backend
    environment:
      REACT_APP_API_BASE_URL: http://localhost:8080
    ports:
      - "3000:3000"

volumes:
  db_data:
